In [4]:
#Pandas
!pip3 install pandas

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (2.3.1)
Requirement already satisfied: numpy>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [7]:
# importing a csv file and printing the first 5 lines including heading using pandas
# df.head defaults to the first 5 lines of the data unless specified
import pandas as pd
df = pd.read_csv("Salary Data.csv")
df.head()

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0

In [6]:
# showing required number of rows from the file
df = pd.read_csv("Salary Data.csv", nrows = 3)
df

   Age  Gender Education Level          Job Title  Years of Experience  Salary
0   32    Male      Bachelor's  Software Engineer                    5   90000
1   28  Female        Master's       Data Analyst                    3   65000
2   45    Male             PhD     Senior Manager                   15  150000

In [8]:
#df. tail defaults to the last 5 lines of the data unless specified
df = pd.read_csv("Salary Data.csv")
df.tail()

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
370,35.0,Female,Bachelor's,Senior Marketing Analyst,8.0,85000.0
371,43.0,Male,Master's,Director of Operations,19.0,170000.0
372,29.0,Female,Bachelor's,Junior Project Manager,2.0,40000.0
373,34.0,Male,Bachelor's,Senior Operations Coordinator,7.0,90000.0
374,44.0,Female,PhD,Senior Business Analyst,15.0,150000.0

In [11]:
# showing certain columns
df[["Years of Experience", "Salary"]]

     Years of Experience    Salary
0                    5.0   90000.0
1                    3.0   65000.0
2                   15.0  150000.0
3                    7.0   60000.0
4                   20.0  200000.0
..                   ...       ...
370                  8.0   85000.0
371                 19.0  170000.0
372                  2.0   40000.0
373                  7.0   90000.0
374                 15.0  150000.0

[375 rows x 2 columns]

In [14]:
# iloc (index localizer)
# Here we are showing values from 5th to 10th index. the 10th value will not be displayed
df.iloc[5:10]

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
5,29.0,Male,Bachelor's,Marketing Analyst,2.0,55000.0
6,42.0,Female,Master's,Product Manager,12.0,120000.0
7,31.0,Male,Bachelor's,Sales Manager,4.0,80000.0
8,26.0,Female,Bachelor's,Marketing Coordinator,1.0,45000.0
9,38.0,Male,PhD,Senior Scientist,10.0,110000.0

In [15]:
# Here the first value 5:10 is for selecting rows and the second 0:4 is for selecting columns
df.iloc[5:10, 0:4]

    Age  Gender Education Level              Job Title
5  29.0    Male      Bachelor's      Marketing Analyst
6  42.0  Female        Master's        Product Manager
7  31.0    Male      Bachelor's          Sales Manager
8  26.0  Female      Bachelor's  Marketing Coordinator
9  38.0    Male             PhD       Senior Scientist

In [20]:
#filter
#single brackets only work when there is only one value
df['Age']

0      32.0
1      28.0
2      45.0
3      36.0
4      52.0
       ...
370    35.0
371    43.0
372    29.0
373    34.0
374    44.0
Name: Age, Length: 375, dtype: float64

In [21]:
#filter by age number
df['Age'] > 34

0      False
1      False
2       True
3       True
4       True
       ...
370     True
371     True
372    False
373    False
374     True
Name: Age, Length: 375, dtype: bool

In [22]:
#filter
#This only shows data with age over 34 years old
df[df["Age"]>34]

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
6,42.0,Female,Master's,Product Manager,12.0,120000.0
9,38.0,Male,PhD,Senior Scientist,10.0,110000.0
...,...,...,...,...,...,...
367,41.0,Male,Bachelor's,Senior Product Manager,14.0,150000.0
368,44.0,Female,PhD,Senior Data Engineer,16.0,160000.0
370,35.0,Female,Bachelor's,Senior Marketing Analyst,8.0,85000.0
371,43.0,Male,Master's,Director of Operations,19.0,170000.0
374,44.0,Female,PhD,Senior Business Analyst,15.0,150000.0

In [25]:
# showing data with age over 40 and has an education level equal to PhD
df[(df['Age'] > 40) & (df["Education Level"] == "PhD")]

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
28,43.0,Female,PhD,Senior Consultant,15.0,140000.0
34,46.0,Male,PhD,Senior Manager,20.0,170000.0
57,43.0,Male,PhD,Senior Engineer,17.0,140000.0
63,47.0,Male,PhD,Senior Data Scientist,21.0,180000.0
72,45.0,Male,PhD,Research Director,16.0,190000.0
83,52.0,Male,PhD,Chief Technology Officer,24.0,250000.0
96,47.0,Male,PhD,Research Scientist,22.0,160000.0
105,44.0,Male,PhD,Chief Data Officer,16.0,220000.0
117,48.0,Male,PhD,Principal Engineer,20.0,170000.0
124,44.0,Female,PhD,Senior Scientist,16.0,140000.0
133,47.0,Male,PhD,Senior Research Scientist,22.0,160000.0
146,42.0,Female,PhD,Senior Data Scientist,16.0,150000.0
152,43.0,Female,PhD,Senior Product Designer,18.0,140000.0
158,51.0,Female,PhD,Director of Human Resources,23.0,185000.0
167,46.0,Male,PhD,Senior Researcher,18.0,150000.0
176,42.0,Female,PhD,Senior Marketing Manager,18.0,140000.0
182,44.0,Female,PhD,Senior UX Designer,15.0,145000.0
188,50.0,Female,PhD,Director of Sales and Marketing,22.0,180000.0
197,45.0,Male,PhD,Senior Data Analyst,17.0,155000.0
205,41.0,Female,PhD,Senior Marketing Director,17.0,160000.0
211,45.0,Female,PhD,Senior Product Designer,15.0,150000.0
217,50.0,Female,PhD,Director of Operations,22.0,180000.0
226,46.0,Male,PhD,Senior Data Scientist,18.0,160000.0
234,42.0,Female,PhD,Senior Marketing Manager,13.0,140000.0
240,44.0,Female,PhD,Senior HR Manager,18.0,160000.0
243,46.0,Male,PhD,Senior Data Analyst,19.0,150000.0
252,45.0,Female,PhD,Senior Product Designer,15.0,150000.0
258,50.0,Female,PhD,Director of Operations,22.0,180000.0
262,46.0,Male,PhD,Senior Data Scientist,18.0,160000.0
270,45.0,Male,PhD,Senior Data Engineer,16.0,150000.0
276,46.0,Male,PhD,Senior Data Analyst,17.0,160000.0
285,44.0,Female,PhD,Senior Product Designer,15.0,150000.0
291,49.0,Male,PhD,Director of Operations,21.0,180000.0
297,44.0,Male,PhD,Senior Data Scientist,16.0,160000.0
303,45.0,Male,PhD,Senior Data Engineer,16.0,150000.0
312,44.0,Female,PhD,Senior Product Designer,15.0,150000.0
323,47.0,Male,PhD,Director of Engineering,20.0,180000.0
326,43.0,Female,PhD,Senior Data Scientist,15.0,150000.0
332,45.0,Female,PhD,Senior UX Designer,16.0,160000.0
338,44.0,Female,PhD,Senior Business Analyst,15.0,150000.0
344,44.0,Female,PhD,Senior Data Engineer,16.0,160000.0
350,44.0,Female,PhD,Senior Data Scientist,16.0,160000.0
356,45.0,Female,PhD,Senior UX Designer,16.0,160000.0
362,44.0,Female,PhD,Senior Business Analyst,15.0,150000.0
368,44.0,Female,PhD,Senior Data Engineer,16.0,160000.0
374,44.0,Female,PhD,Senior Business Analyst,15.0,150000.0

In [26]:
# showing data with age over 40 or has an education level equal to PhD
df[(df['Age'] > 40) | (df["Education Level"] == "PhD")]

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
4,52.0,Male,Master's,Director,20.0,200000.0
6,42.0,Female,Master's,Product Manager,12.0,120000.0
9,38.0,Male,PhD,Senior Scientist,10.0,110000.0
11,48.0,Female,Bachelor's,HR Manager,18.0,140000.0
...,...,...,...,...,...,...
365,43.0,Male,Master's,Director of Marketing,18.0,170000.0
367,41.0,Male,Bachelor's,Senior Product Manager,14.0,150000.0
368,44.0,Female,PhD,Senior Data Engineer,16.0,160000.0
371,43.0,Male,Master's,Director of Operations,19.0,170000.0
374,44.0,Female,PhD,Senior Business Analyst,15.0,150000.0

In [29]:
# How to convert list into data frame
data = [["Ram", 34, "Kathmandu"],
       ["Shyam",45,"Bhaktapur"],
       ["Hari",34,"Lalitpur"]]
col = ["Name","Age","Address"]
df = pd.DataFrame(data, columns = col)
df

    Name  Age    Address
0    Ram   34  Kathmandu
1  Shyam   45  Bhaktapur
2   Hari   34   Lalitpur

In [32]:
# How to convert dict into data frame
data1 = {'Name':["Ram","Shyam","Hari"],
       'Age':[23, 45, 65],
        'Address':["Kathmandu","Bhaktapur","Lalitpur"]}
df1 = pd.DataFrame(data1)
df1

    Name  Age    Address
0    Ram   23  Kathmandu
1  Shyam   45  Bhaktapur
2   Hari   65   Lalitpur

In [34]:
# Concat two dataframes
data1 = {'Name':["Ram","Shyam","Hari"],
       'Age':[23, 45, 65],
        'Address':["Kathmandu","Bhaktapur","Lalitpur"]}
df1 = pd.DataFrame(data1)

data2 = {'Name':["Ram","Shyam","Hari"],
       'Age':[23, 45, 65],
        'Address':["Kathmandu","Bhaktapur","Lalitpur"]}
df2 = pd.DataFrame(data2)
df = pd.concat([df1,df2])
df

    Name  Age    Address
0    Ram   23  Kathmandu
1  Shyam   45  Bhaktapur
2   Hari   65   Lalitpur
0    Ram   23  Kathmandu
1  Shyam   45  Bhaktapur
2   Hari   65   Lalitpur

In [35]:
df['SN'] = [1,2,3,4,5,6]

In [36]:
df

    Name  Age    Address  SN
0    Ram   23  Kathmandu   1
1  Shyam   45  Bhaktapur   2
2   Hari   65   Lalitpur   3
0    Ram   23  Kathmandu   4
1  Shyam   45  Bhaktapur   5
2   Hari   65   Lalitpur   6

In [39]:
#save the dataframe
df.to_csv("Day15test.csv")

In [40]:
df = pd.read_csv("Day15test.csv", usecols = ["SN","Name","Age","Address"])
df

    Name  Age    Address  SN
0    Ram   23  Kathmandu   1
1  Shyam   45  Bhaktapur   2
2   Hari   65   Lalitpur   3
3    Ram   23  Kathmandu   4
4  Shyam   45  Bhaktapur   5
5   Hari   65   Lalitpur   6